### ISSUE TITLE
Add support for client credentials OAuth flow

### ISSUE THREAD

**Issue by jakeprins** [apideck-libraries/react-vault#31]
https://github.com/apideck-samples/vault/pull/233/files

**Comment by thim81** [comment]
![2022-09-30 at 11 47 15](https://user-images.githubusercontent.com/952446/193244361-8c853471-4e8a-4d95-be22-f82c703effad.png)

**Comment by Gdewilde** [comment]
For Netsuite, we have the same problem. The settings are hidden away but still
required to make a connection. When you click on authorize it shows an error
message. In Hosted Vault, this behavior is different.
Settings should be shown by default if they're required for the auth flow.

​






On Fri, Sep 30, 2022 at 11:51 AM thim81 ***@***.***>  wrote:




—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.Message ID: 
***@***.***>



Gertjan De WildeCEO & co-founderApideck

**Comment by Gdewilde** [comment]
You're correct @jakeprins
